dddd

diff --git a/.github/workflows/build-apk.yml b/.github/workflows/build-apk.yml
--- a/.github/workflows/build-apk.yml
+++ b/.github/workflows/build-apk.yml
@@ -27,6 +27,7 @@ jobs:
               APP_NAME=$(echo "$file" | sed -e 's/https.*apps\///g' | sed -e 's/\/.*//g')
             fi
           done
+          if [ -z ${APP_NAME+x} ]; then echo "APP_NAME not found" && exit 1
       - name: set up JDK 11
         uses: actions/setup-java@v3
         with:
