sssfff

diff --git a/.github/workflows/build-apk.yml b/.github/workflows/build-apk.yml
--- a/.github/workflows/build-apk.yml
+++ b/.github/workflows/build-apk.yml
@@ -23,11 +23,16 @@ jobs:
         run: |
           for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
             echo "$file was changed"
-            if [[ "$file" == *"apps/"* ]]; then
+            if [[ "$file" == "apps/"* ]]; then
+              echo "found app"
               APP_NAME=$(echo "$file" | sed -e 's/https.*apps\///g' | sed -e 's/\/.*//g')
+              echo $APP_NAME
             fi
           done
-          if [ -z ${APP_NAME+x} ]; then echo "APP_NAME not found" && exit 1
+          if [ -z ${APP_NAME+x} ]; then 
+            echo "APP_NAME not found"
+            exit 1
+          fi
       - name: set up JDK 11
         uses: actions/setup-java@v3
         with:
